# Usage example:
#
# $ docker-compose up -d
# $ docker-compose exec mysql mysql -u test -ptest test
#
version: '3'

services:
  mysql:
    image: mysql:5.7.20
    user: mysql:mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
    volumes:
      - ./categories.mysql.sql:/docker-entrypoint-initdb.d/categories.sql

